### ISSUE TITLE
support topic in producer$send?

### ISSUE THREAD

**Issue by r2evans** [dselivanov/rscalaKafka#3]
Looking at the source for `RscalaKafkaProducer$send`, it appears that `topic` is hard-coded from the instantiation. Is it possible to add `topic` as an argument to `$send`, defaulting to the original topic if not provided? (I believe it is reasonable for a single producer to be able to send to multiple topics. Please tell me if there is rationale against this behavior.)

**Comment by dselivanov** [comment]
Good point. No rationale for this. I will take a look (I only started to learn kafka, so some design things can be wrong).
